[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["corepack enable", "pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm exec prisma generate", "pnpm build"]

[start]
cmd = "pnpm run start:zeabur"
